@baseURL = http://localhost:2313/api/v1/inventory
@token=60717570d725a90bc87eff4a1f4f0dac490e532546def7ce9534770fa9dcefc3d20ca3c43767f5e6c75479c92b5befaa

GET {{baseURL}}
Content-Type: application/json
Authorization: Bearer {{token}}


##########
POST {{baseURL}}/3/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "quantity":10
}

####

DELETE {{baseURL}}/1
Content-Type: application/json
Authorization: Bearer {{token}}

####

PUT {{baseURL}}/1/1/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "quantity":1
}

