@baseURL = http://localhost:2313/api/v1/permissions


GET {{baseURL}}
Content-Type: application/json



##########
POST {{baseURL}}
Content-Type: application/json

{
    "title":"bookstore",
    "priority":1

}

####
PUT {{baseURL}}/6
Content-Type: application/json

{
    "title":"bookstore",
    "priority":null

}
