@baseURL = http://localhost:2313/api/v1/permission-item


GET {{baseURL}}
Content-Type: application/json



##########
POST {{baseURL}}/5
Content-Type: application/json

{
    "title":"hi_dssense",
    "priority":4
}

####
PUT {{baseURL}}/2/5
Content-Type: application/json

{
    "title":"hi_world"
}


####
DELETE {{baseURL}}/5/15
Content-Type: application/json


