@baseURL = http://localhost:2313/api/v1/permission-item


GET {{baseURL}}
Content-Type: application/json



##########
POST {{baseURL}}/1
Content-Type: application/json

{
    "title":"move",
    "priority":4
}

####
PUT {{baseURL}}/6/46
Content-Type: application/json

{
    "title":"move",
    "priority":1120

}


####
DELETE {{baseURL}}/6/46
Content-Type: application/json


